exports.Columns = {
text: require("../../fields/types/text/TextColumn"),
html: require("../../fields/types/html/HtmlColumn"),
file: require("../../fields/types/file/FileColumn"),
vimeo: require("../../fields/types/vimeo/VimeoColumn"),
cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageColumn"),
relationship: require("../../fields/types/relationship/RelationshipColumn"),
select: require("../../fields/types/select/SelectColumn"),
number: require("../../fields/types/number/NumberColumn"),
textarray: require("../../fields/types/textarray/TextArrayColumn"),
name: require("../../fields/types/name/NameColumn"),
email: require("../../fields/types/email/EmailColumn"),
password: require("../../fields/types/password/PasswordColumn"),
boolean: require("../../fields/types/boolean/BooleanColumn"),
id: require("../../fields/components/columns/IdColumn"),
__unrecognised__: require("../../fields/components/columns/InvalidColumn"),
};
exports.Fields = {
text: require("../../fields/types/text/TextField"),
html: require("../../fields/types/html/HtmlField"),
file: require("../../fields/types/file/FileField"),
vimeo: require("../../fields/types/vimeo/VimeoField"),
cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageField"),
relationship: require("../../fields/types/relationship/RelationshipField"),
select: require("../../fields/types/select/SelectField"),
number: require("../../fields/types/number/NumberField"),
textarray: require("../../fields/types/textarray/TextArrayField"),
name: require("../../fields/types/name/NameField"),
email: require("../../fields/types/email/EmailField"),
password: require("../../fields/types/password/PasswordField"),
boolean: require("../../fields/types/boolean/BooleanField"),
};
exports.Filters = {
text: require("../../fields/types/text/TextFilter"),
html: require("../../fields/types/html/HtmlFilter"),
file: require("../../fields/types/file/FileFilter"),
vimeo: require("../../fields/types/vimeo/VimeoFilter"),
cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageFilter"),
relationship: require("../../fields/types/relationship/RelationshipFilter"),
select: require("../../fields/types/select/SelectFilter"),
number: require("../../fields/types/number/NumberFilter"),
textarray: require("../../fields/types/textarray/TextArrayFilter"),
name: require("../../fields/types/name/NameFilter"),
email: require("../../fields/types/email/EmailFilter"),
password: require("../../fields/types/password/PasswordFilter"),
boolean: require("../../fields/types/boolean/BooleanFilter"),
};
