exports.Columns = {
    text: require("../../fields/types/text/TextColumn"),
    html: require("../../fields/types/html/HtmlColumn"),
    cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageColumn"),
    cloudinaryimages: require("../../fields/types/cloudinaryimages/CloudinaryImagesColumn"),
    relationship: require("../../fields/types/relationship/RelationshipColumn"),
    select: require("../../fields/types/select/SelectColumn"),
    number: require("../../fields/types/number/NumberColumn"),
    name: require("../../fields/types/name/NameColumn"),
    email: require("../../fields/types/email/EmailColumn"),
    password: require("../../fields/types/password/PasswordColumn"),
    boolean: require("../../fields/types/boolean/BooleanColumn"),
    id: require("../../fields/components/columns/IdColumn"),
    __unrecognised__: require("../../fields/components/columns/InvalidColumn"),
};
exports.Fields = {
    text: require("../../fields/types/text/TextField"),
    html: require("../../fields/types/html/HtmlField"),
    cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageField"),
    cloudinaryimages: require("../../fields/types/cloudinaryimages/CloudinaryImagesField"),
    relationship: require("../../fields/types/relationship/RelationshipField"),
    select: require("../../fields/types/select/SelectField"),
    number: require("../../fields/types/number/NumberField"),
    name: require("../../fields/types/name/NameField"),
    email: require("../../fields/types/email/EmailField"),
    password: require("../../fields/types/password/PasswordField"),
    boolean: require("../../fields/types/boolean/BooleanField"),
};
exports.Filters = {
    text: require("../../fields/types/text/TextFilter"),
    html: require("../../fields/types/html/HtmlFilter"),
    cloudinaryimage: require("../../fields/types/cloudinaryimage/CloudinaryImageFilter"),
    cloudinaryimages: require("../../fields/types/cloudinaryimages/CloudinaryImagesFilter"),
    relationship: require("../../fields/types/relationship/RelationshipFilter"),
    select: require("../../fields/types/select/SelectFilter"),
    number: require("../../fields/types/number/NumberFilter"),
    name: require("../../fields/types/name/NameFilter"),
    email: require("../../fields/types/email/EmailFilter"),
    password: require("../../fields/types/password/PasswordFilter"),
    boolean: require("../../fields/types/boolean/BooleanFilter"),
};